{% set version = "1.0.0" %}

package:
  name: spacy-pkuseg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spacy-pkuseg/spacy_pkuseg-{{ version }}.tar.gz
  sha256: 33531ea8e13fc09ebe3b40bd97e84d07ccd5a1fe67fa8e84173769a25ac03158

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - srsly >=2.3.0,<3.0.0

test:
  imports:
    - spacy_pkuseg
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -m pytest -vv --color=yes --tb=native --pyargs spacy_pkuseg

about:
  home: http://github.com/explosion/spacy-pkuseg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PKUSeg Chinese word segmentation toolkit for spaCy

extra:
  recipe-maintainers:
    - conda-forge/spacy
