{% set name = "spacy-pkuseg" %}
{% set modulename = "spacy_pkuseg" %}
{% set version = "0.0.33" %}
{% set sha256sum = "f13156ac4e04460f1ac35edfd036e99704dbbad19ad0a39b06c340f802a29e62" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ modulename }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy
  run:
    - python
    - srsly >=2.3.0,<3.0.0
    - cython

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ modulename }}

about:
  home: http://github.com/explosion/spacy-pkuseg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PKUSeg Chinese word segmentation toolkit for spaCy

  doc_url: https://github.com/explosion/spacy-pkuseg
  dev_url: https://github.com/explosion/spacy-pkuseg

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
