{% set name = "spacy-pkuseg" %}
{% set modulename = "spacy_pkuseg" %}
{% set version = "1.0.0" %}
{% set sha256sum = "33531ea8e13fc09ebe3b40bd97e84d07ccd5a1fe67fa8e84173769a25ac03158" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/{{ name }}/{{ modulename }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - srsly >=2.3.0,<3.0.0
    - cython

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ modulename }}

about:
  home: http://github.com/explosion/spacy-pkuseg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PKUSeg Chinese word segmentation toolkit for spaCy

  doc_url: https://github.com/explosion/spacy-pkuseg
  dev_url: https://github.com/explosion/spacy-pkuseg

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
